#  ------------------------------------    CONFIGS   -------------------------------------------------------------------
collect_info: true
results_dir: /tmp/perf_tests
settings_dir: ~/.wally
connect_timeout: 30
download_rpc_logs: true
rpc_log_level: INFO
default_test_local_folder: "/tmp/wally_{uuid}_{name}"
keep_raw_files: false

logging:
    level: DEBUG
#   config: logger.yaml

vm_configs:
    keypair_file_private: wally_vm_key_perf3.pem
    keypair_file_public: wally_vm_key_perf3.pub
    keypair_name: wally_vm_key

    wally_1024:
        image:
            name: wally_ubuntu
            user: ubuntu
            url: https://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img

        flavor:
            name: wally_1024
            hdd_size: 100
            ram_size: 1024
            cpu_count: 2

        vol_sz: 100
        name_templ: wally-{group}-{id}
        aa_group_name: wally-aa-{0}
        security_group: wally_ssh_to_everyone


ceph_settings: nodeep-scrub, noscrub

#-----------------------------------------    STEPS   ------------------------------------------------------------------

sensors:
   online: true
   roles_mapping:
       testnode: system-cpu, block-io, net-io
       ceph-osd:
            system-cpu: ".*"
            block-io: ".*"
            net-io: ".*"
            ceph:
                counters:
                  - osd/op_r
                  - osd/op_w
                  - osd/op_r_out_bytes
                  - osd/op_w_in_bytes
       compute:
            system-cpu: ".*"
            block-io: "sd?"
            net-io: ".*"

#----------------------------------   TEST PROFILES --------------------------------------------------------------------
profiles:
    spawn:
        OS_1_to_1:
            openstack:
                count: "=1"
                cfg_name: wally_1024
                network_zone_name: net04
                flt_ip_pool: net04_ext
                skip_preparation: true

    test:
        ceph_vdb:
            - io:
                load: ceph
                params:
                    FILENAME: /dev/vdb
                    TEST_FILE_SIZE: AUTO

        cinder_iscsi_vdb:
            - io:
                load: cinder_iscsi
                params:
                    FILENAME: /dev/vdb
                    TEST_FILE_SIZE: AUTO

        nova_io:
            - io:
                load: hdd
                params:
                    FILENAME: /dev/vdb
                    TEST_FILE_SIZE: AUTO

    openstack_ceph: OS_1_to_1 + ceph_vdb
    openstack_cinder: OS_1_to_1 + ceph_iscsi_vdb
    openstack_nova: OS_1_to_1 + nova_io


reporting:
    colors:
        primary_color: b
        suppl_color1: teal
        suppl_color2: magenta
        box_color: y
        noise_alpha: 0.3
        subinfo_alpha: 0.7
        imshow_colormap: null

    style:
        grid: true
        tide_layout: true
        hist_boxes: 10
        min_points_for_dev: 5
        dev_range_x: 2.0
        dev_perc: 95
        avg_range: 20
        curve_approx_level: 5
        curve_approx_points: 100
        extra_io_spine: true
        legend_for_eng: True
        heatmap_interpolation: 1d
        heatmap_interpolation_points: 300
        outliers_q_nd: 3.0
        outliers_lat: [0.01, 0.995]
        violin_instead_of_box: true
        violin_point_count: 30000
        heatmap_colorbar: false
        units:
            bw: ["MiBps", 1024, "bandwith"]
            iops: ["IOPS", 1, "iops"]
            lat: ["ms", 1, "latency"]

    matplotlib_params:
        "font.size": 10