sensors:
    roles_mapping:
        testnode: system-cpu, block-io
        compute: system-cpu
        ceph-osd: system-cpu, block-io

internal:
    var_dir_root: /tmp/perf_tests

explicit_nodes:
    # "ssh://ubuntu@216.221.229.20::/root/disk_perf_test_tool/disk_io_perf.pem": testnode
    # "ssh://ubuntu@216.221.229.21::/root/disk_perf_test_tool/disk_io_perf.pem": testnode
    # "ssh://ubuntu@216.221.229.18::/root/disk_perf_test_tool/disk_io_perf.pem": testnode
    # "ssh://ubuntu@216.221.229.17::/root/disk_perf_test_tool/disk_io_perf.pem": testnode
    # "ssh://ubuntu@216.221.229.19::/root/disk_perf_test_tool/disk_io_perf.pem": testnode
    # "ssh://ubuntu@216.221.229.22::/root/disk_perf_test_tool/disk_io_perf.pem": testnode
    "ssh://node-8": compute
    "ssh://node-9": compute
    "ssh://node-10": compute
    "ssh://node-5": ceph-osd
    "ssh://node-7": ceph-osd
    "ssh://node-13": ceph-osd

vm_configs:
    wally_1024:
        image:
            name: wally_ubuntu
            url: https://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img
            creds: "ssh://ubuntu@{ip}::{private_key_path}"

        flavor:
            name: wally_1024
            hdd_size: 50
            ram_size: 1024
            cpu_count: 1

        vol_sz: 30
        keypair_name: wally_vm_key
        name_templ: wally-{group}-{id}
        aa_group_name: wally-aa-{0}
        security_group: wally_ssh_to_everyone

tests:
    - start_test_nodes:
        openstack:
            creds: ENV
            count: x1
            cfg_name: wally_1024
            network_zone_name: net04
            flt_ip_pool: net04_ext

        tests:
            - io:
                cfg: ceph
                params:
                    FILENAME: /dev/vdb
                    NUM_ROUNDS: 7

logging:
    extra_logs: 1
