clouds:
    ceph: local

discover: ceph

explicit_nodes:
    "ssh://koder@192.168.152.43::/home/koder/.ssh/id_rsa": testnode

internal:
    var_dir_root: /tmp/perf_tests

sensors:
    receiver_url: "udp://{ip}:5699"
    roles_mapping:
        ceph-osd: block-io
        cinder: block-io, system-cpu
        testnode: system-cpu, block-io

tests:
    - io:
        # cfg: tests/io_scenario_hdd.cfg
        cfg: scripts/fio_tests_configs/io_task_test.cfg
        params:
            FILENAME: /mnt/ceph/xxx.bin
            NUM_ROUNDS: 7

logging:
    extra_logs: 1
