clouds:
    fuel:
        url: http://172.16.52.112:8000/
        creds: admin:admin@admin
        ssh_creds: root:test37
        openstack_env: Performance-1

discover: fuel

# explicit_nodes:
#     "ssh://root@172.16.52.112:3022:/home/koder/.ssh/id_rsa": testnode

internal:
    var_dir_root: /tmp/perf_tests

# sensors:
#     roles_mapping:
#         ceph-osd: block-io
#         cinder: block-io, system-cpu
#         testnode: system-cpu, block-io

tests:
    - start_test_nodes:
        creds: clouds
        vm_params:
            count: x1
            image:
                name: disk_io_perf
                url: https://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img

            flavor:
                name: disk_io_perf.1024
                hdd_size: 50
                ram_size: 1024
                cpu: 1

            vol_sz: 30
            keypair_name: disk_io_perf
            network_zone_name: novanetwork
            flt_ip_pool: nova
            private_key_path: disk_io_perf.pem
            creds: "ssh://ubuntu@{ip}::{private_key_path}"
            name_templ: wally-{group}-{id}
            scheduler_group_name: wally-{group}-{id}
            security_group: disk_io_perf

        tests:
            - io:
                name: ceph
                # cfg: wally/suits/io/io_scenario_ceph.cfg
                cfg: scripts/fio_tests_configs/io_task_test.cfg
                prefill_files: true
                params:
                    FILENAME: /dev/vdb
                    NUM_ROUNDS: 3
# 
#     - io:
#         # cfg: scripts/fio_tests_configs/io_task_test.cfg
#         cfg: tests/io_scenario_hdd.cfg
#         params:
#             # FILENAME: /media/koder/a5230078-4c27-4c3b-99aa-26148e78b2e7/xxx.bin
#             FILENAME: /opt/xxx.bin
#             NUM_ROUNDS: 7

logging:
    extra_logs: 1