clouds:
    fuel:
        url: http://172.16.52.113:8000/
        creds: admin:admin@admin
        ssh_creds: root:test37
        openstack_env: rrr

discover: fuel

internal:
    var_dir_root: /tmp/perf_tests

tests:
    - start_test_nodes:
        creds: clouds
        vm_params:
            count: x1
            image:
                name: disk_io_perf
                url: https://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img

            flavor:
                name: disk_io_perf.1024
                hdd_size: 50
                ram_size: 1024
                cpu: 1

            vol_sz: 30
            keypair_name: disk_io_perf
            network_zone_name: net04
            flt_ip_pool: net04_ext
            private_key_path: disk_io_perf.pem
            creds: "ssh://ubuntu@{ip}::{private_key_path}"
            name_templ: wally-{group}-{id}
            scheduler_group_name: wally-{group}-{id}
            security_group: disk_io_perf

        tests:
            - io:
                cfg: wally/suits/io/ceph.cfg
                prefill_files: true
                params:
                    FILENAME: /dev/vdb
                    NUM_ROUNDS: 1

logging:
    extra_logs: 1