explicit_nodes:
    local: testnode

internal:
    var_dir_root: /tmp/perf_tests

sensors:
    receiver_url: "udp://{ip}:5699"
    roles_mapping:
        ceph-osd: block-io
        cinder: block-io, system-cpu
        testnode: system-cpu, block-io

tests:
    - io:
        cfg: wally/suits/io/io_scenario_hdd.cfg
        prefill_files: false
        params:
            FILENAME: /media/koder/a5230078-4c27-4c3b-99aa-26148e78b2e7/xxx.bin
            NUM_ROUNDS: 3

logging:
    extra_logs: 1