explicit_nodes:
    # local: testnode
    "ssh://koder@koder-gup::/home/koder/.ssh/id_rsa": testnode

internal:
    var_dir_root: /tmp/perf_tests

testnode_log_root: /tmp/perf_tests_rem
# run_web_ui: true

# sensors:
#     roles_mapping:
#         testnode: system-cpu, block-io

tests:
    - io:
        cfg: wally/suits/io/hdd.cfg
        # cfg: scripts/fio_tests_configs/io_task_test.cfg
        prefill_files: false
        use_sudo: false
        test_logging: true
        params:
            FILENAME: /media/koder/a5230078-4c27-4c3b-99aa-26148e78b2e7/xxx.bin
            NUM_ROUNDS: 7

logging:
    extra_logs: 1